Feature/initialize project
norsys-2019/norsys-archetype pull request #3
Opened 2019-03-17 19:09 UTC by melbied

Ajout des dépendances
Modification du nommage des packages

2019-03-18 16:18 UTC, ammach reviewed
il faudra aussi: 
- ajouter la structure de projet comme dans l'image suivante
![Clipboard - 18 mars 2019 12_09](https://user-images.githubusercontent.com/12902041/54545270-42242600-4999-11e9-9a9b-de7e9bde6d51.png)
- Modifier le fichier readme et mettre la commande pour expliquer la façon de générer un projet

2019-03-18 16:18 UTC, ammach commented on .classpath
> +<?xml version="1.0" encoding="UTF-8"?>
:x: il faudra mettre ce fichier dans le .gitignore

2019-03-18 16:18 UTC, ammach commented on .project
> +<?xml version="1.0" encoding="UTF-8"?>
:x: il faudra mettre ce fichier dans le .gitignore

2019-03-18 16:18 UTC, ammach commented on .settings/org.eclipse.jdt.apt.core.prefs
> +eclipse.preferences.version=1
idem

2019-03-18 16:18 UTC, ammach commented on .settings/org.eclipse.jdt.core.prefs
> +eclipse.preferences.version=1
idem

2019-03-18 16:18 UTC, ammach commented on .settings/org.eclipse.m2e.core.prefs
> +activeProfiles=
idem

2019-03-22 08:09 UTC, ammach commented
il manque la mise à jour du fichier readme avec la commande (ligne de commande) pour créer un projet à partir du archetype

2019-03-22 14:23 UTC, ammach requested changes

2019-03-22 14:23 UTC, ammach commented on README.md
> +mvn archetype:generate -DarchetypeGroupId=fr.norsys.sinaf -DarchetypeArtifactId=sinaf-archetype -DarchetypeVersion=1.0
:point_right: il faudrait ajouter 2 paramètres pour ta commande:
- la première pour donner le nom du microservice
- la deuxième pour donner le port sur lequel sera déployer le microservice

2019-03-22 21:59 UTC, melbied commented on README.md
> +mvn archetype:generate -DarchetypeGroupId=fr.norsys.sinaf -DarchetypeArtifactId=sinaf-archetype -DarchetypeVersion=1.0
@ammach 
Concernant le port de déploiement et le nom sont spécifiés dans application.properties

2019-03-26 07:52 UTC, ammach commented
le fait de saisir le **nom du projet** et le **port** **dans application.properties** n'est pas top, j'aurais préféré d'entrer ces infos depuis la commande de génération du projet, il faut faire quelque chose comme ça :
```
mvn archetype:generate -DarchetypeGroupId=fr.norsys.sinaf -DarchetypeArtifactId=sinaf-archetype -DarchetypeVersion=1.0 -DserviceName=formation -DservicePort=8090
```

2019-04-01 17:11 UTC, ammach requested changes

2019-04-01 17:11 UTC, ammach commented on README.md
> +  git checkout Feature/initialize project
:thinking: pourqui il faut faire un checkout à cette branche ??

2019-04-01 17:11 UTC, ammach commented on README.md
> +Etape 1:
il faut écrire le readme en anglais

2019-04-01 17:11 UTC, ammach commented on README.md
> +  Importer l'archetype depuis git avec les commandes suivantes:
pas la peine d'écrire cette phrase , on sait qu'est ce qu'elle fait :wink:, il vaut mieux écrire comme ça:
**Step1:**  Run the following commands:
   `git clone https://github.com/norsys-2019/norsys-archetype.git`
`cd norsys-archetype`
`mvn install`
**Step2:** Generate the project
`mvn archetype:generate -DarchetypeGroupId=fr.norsys.sinaf -DarchetypeArtifactId=sinaf-archetype -DarchetypeVersion=1.0 -Dname=xxxx -Dport=xxxx`

![tableauparam](https://user-images.githubusercontent.com/48215221/55246525-aec6dc80-5245-11e9-91ee-83a500ea16d9.PNG)

2019-04-03 16:59 UTC, merged